# Generated by Django 2.0.2 on 2018-02-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_number', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Deal Number')),
                ('ann_date', models.DateField(verbose_name='Announced Date')),
                ('effective_date', models.DateTimeField(blank=True, null=True, verbose_name='Effective Date')),
                ('cancel_date', models.DateTimeField(blank=True, null=True, verbose_name='Cancel Date')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Total Deal Value')),
                ('acq_companyName', models.CharField(max_length=200, verbose_name='Acq Company Name')),
                ('acq_country', models.CharField(max_length=3, verbose_name='Acq Country Code')),
                ('acq_sector', models.CharField(max_length=200, verbose_name='Acq Sector')),
                ('tar_companyName', models.CharField(max_length=200, verbose_name='Tar Company Name')),
                ('tar_country', models.CharField(max_length=3, verbose_name='Tar Country Code')),
                ('tar_sector', models.CharField(max_length=200, verbose_name='Tar Sector')),
            ],
        ),
        migrations.CreateModel(
            name='DealHistory',
            fields=[
                ('poke_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_poked', models.DateTimeField(verbose_name='Datetime Poked')),
            ],
        ),
    ]
