# Generated by Django 2.0.2 on 2018-02-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_number', models.CharField(max_length=200, verbose_name='Deal Number')),
                ('ann_date', models.DateTimeField(verbose_name='Announced Date')),
                ('effective_date', models.DateTimeField(verbose_name='Effective Date')),
                ('cancel_date', models.DateTimeField(verbose_name='Cancel Date')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Total Deal Value')),
                ('acq_companyName', models.CharField(max_length=200, verbose_name='Acq Company Name')),
                ('acq_country', models.CharField(max_length=3, verbose_name='Acq Country Code')),
                ('acq_sector', models.CharField(max_length=200, verbose_name='Acq Sector')),
                ('tar_companyName', models.CharField(max_length=200, verbose_name='Tar Company Name')),
                ('tar_country', models.CharField(max_length=3, verbose_name='Tar Country Code')),
                ('tar_sector', models.CharField(max_length=200, verbose_name='Tar Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vale', models.CharField(max_length=200, verbose_name='Value to Poke In')),
                ('field', models.CharField(max_length=200, verbose_name='Field to Poke')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.Deal')),
            ],
        ),
    ]
