# Generated by Django 2.0.2 on 2018-02-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealhistory',
            name='poke_id',
        ),
        migrations.AlterField(
            model_name='dealhistory',
            name='deal_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CRUD.Deal'),
        ),
    ]
