# Generated by Django 2.0.2 on 2018-02-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancel Date'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='effective_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Effective Date'),
        ),
    ]
